{{- if .Values.exporter.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: skydive-exporter-secret
type: Opaque
data:
  accesskey: {{ .Values.exporter.write.s3.access_key | b64enc}}
  secretkey: {{ .Values.exporter.write.s3.secret_key | b64enc}}
  apikey: {{ .Values.exporter.write.s3.api_key | b64enc}}
{{- end }}
