apiVersion: charts.helm.k8s.io/v1alpha1
kind: NetflowCollector
metadata:
  name: netflow-collector
spec:
  exporter:
    enabled: true
    classify:
      # to turn on autodiscovery of cluster netmasks use "subnet_autodiscovery" value; 
      # to turn off auto-discovery set the value to "subnet"
      type: "subnet_autodiscovery"
      # In case subnet_autodiscovery is set, value should include only the private netmasks.
      # if autodiscovery is off, set the value to the complete list of netmasks to be used
      cluster_net_masks: "10.0.0.0/8 172.16.0.0/12 192.168.0.0/16"
    store:
      bucket: "default"
      objectPrefix: "default"
    write:
      s3:
        #endpoint is a required value, pointing to a working Object Store endpoint Example value - "http://localhost:9000"
        endpoint: "http://localhost:9000"
        #installLocalMinio should be set to false. If set to true a default minio OS will be installed locally (in a container) for testing purposes only.
        installLocalMinio: true
        region: "default"
        use_api_key: false
        api_key: ""
        access_key: "admin"
        secret_key: "admin1234"
