apiVersion: apps/v1
kind: Deployment
metadata:
  name: skydive-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: skydive-operator
  template:
    metadata:
      labels:
        name: skydive-operator
    spec:
      serviceAccountName: skydive-operator
      containers:
        - name: skydive-operator
          image: quay.io/sacloud/skydive-op:v0.0.8
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "skydive-operator"
